# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 930eb3ea0a1c32df80b3125146c04e6c694058796dff6f40bf913a46b5d38fabd519f50e2c8fdc7808b44e6737044984caae948d9a628b23e0f4b41109c06163

test:
  secret_key_base: 9ccea31786630b1f0aa033a2a302f2c405aec00d7bd6f86a4343aced4048d49e62e53f4e59140b6d9c4483383757c0c75231047b9a27361597e73a4d0770758c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
